---
title: "SKTdatahub"
author: "Kang Gyeonghun"
date: "10/28/2020"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float:
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      root.dir = dirname(rstudioapi::getActiveDocumentContext()$path))
dirname(rstudioapi::getActiveDocumentContext()$path)
```

<br>

**한글 데이터 읽기 위해 System locale 전환**
```{r}
oldloc = Sys.getlocale("LC_ALL")
Sys.setlocale("LC_ALL", "korean")
```


<br>

**필요한 패키지들 불러오기**
```{r, results='hide', warning=FALSE, message=FALSE}
pkgs = c('tidyverse','ggplot2','jsonlite','httr', 'urltools', "lubridate", "data.table")
pkg_ins = rownames(installed.packages())
for(pkg in pkgs){  if(!(pkg %in% pkg_ins)) install.packages(pkg, character.only=T) }
sapply(pkgs, library, character.only=T)
```

```{r}
citycodes = fread("data/citycode.csv", encoding = "UTF-8")
seoulCode = rbind(citycodes[1:24,], tail(citycodes,1))
seoulCode
```


## API로 데이터 가져오기

### 서울시 배달업종별 이용통화량


```{r}
pids = c(1002231, 1002202, 1002174, 1002145, 1002119, 1002094, 1002055, 1002050, 1002027, 1001997, 1001976, 1001956,
  1001934, 1001913, 1001892, 1001868, 1001856, 1001831, 1001814, 1001785, 1001764, 1001743, 1001722, 1001698,
  1001681, 1001633, 1001602, 1001582, 1001561, 1001534, 1001517, 1001485, 1001469)
pids = pids[length(pids):1]
years = c("17", "18")
pids_names = c()
for(year in years){pids_names = c(pids_names, paste(year, month.name))}
pids_names = c(pids_names, paste("19", month.name[1:9]))
names(pids) = pids_names
pids
```
```{r}
operation = "https://api.bigdatahub.co.kr/v1/datahub/datasets/search.json"
key = "c23859edf3c74322cef63f0aeac9e154c89f9e66e307032042a02c26da5265e4"

call1719raw = data.frame()
for (pid in pids[12]) {
  cat(pid, "\n")
  for (i in 1:10000) {
    params = list(
      pid = pid,
      TDCAccessKey = key,
      "$page" = i,
      "$count" = 300
    )
    result = GET(operation, query = params) %>% content("text") %>% fromJSON(flatten = T)
    call1719raw = rbind(call1719raw, result$entry)
    cat((i*300), "\t")
    if((i*300) >= result$totalResult) break
    NOW = Sys.time()
    while ((as.numeric(Sys.time()) - as.numeric(NOW)) < 0.0001) {}
  }
  NOW = Sys.time()
  while ((as.numeric(Sys.time()) - as.numeric(NOW)) < 0.1) {}
}
call1719raw
```

```{r}
write.table(call1719raw, "data/call-1701-1711raw.csv", sep=",", row.names = F, fileEncoding = "UTF-8")
```


17년 11월까지는 갖고옴.. 중간에 에러남.. 일단 17년 12월 따로 모으고...

```{r}
operation = "https://api.bigdatahub.co.kr/v1/datahub/datasets/search.json"
key = "c23859edf3c74322cef63f0aeac9e154c89f9e66e307032042a02c26da5265e4"

call1712raw = data.frame()
for (pid in pids[12]) {
  cat(pid, "\n")
  for (i in 1:1000) {
    params = list(
      pid = pid,
      TDCAccessKey = key,
      "$page" = i,
      "$count" = 300
    )
    result = GET(operation, query = params) %>% content("text") %>% fromJSON(flatten = T)
    call1712raw = rbind(call1712raw, result$entry)
    cat((i*300), "\t")
    if((i*300) >= result$totalResult) break
    NOW = Sys.time()
    while ((as.numeric(Sys.time()) - as.numeric(NOW)) < 0.00001) {}
  }
  NOW = Sys.time()
  while ((as.numeric(Sys.time()) - as.numeric(NOW)) < 0.1) {}
}
call1712raw
```

```{r}
call17raw = rbind(call1719raw, call1712raw)
write.table(call17raw, "data/call17raw.csv", sep=",", row.names = F, fileEncoding = "UTF-8")
```

ㅅㅂ 그냥 csv 받는다 ㅅㅂ..

```{r}
call1819raw = data.table()
months = c(1801:1812, 1901:1909)
for(month in months){
  path = paste0("call_ndelivery/", month, ".csv")
  call1819raw = rbind(call1819raw, fread(path, encoding = "UTF-8"))
}
call1819raw
```

```{r}
# call171819raw = rbind(call17raw, call1819raw)
# write.table(call171819raw, "data/call171819raw.csv", sep=",", row.names = F, fileEncoding = "UTF-8")
call171819raw = fread("data/call171819raw.csv", encoding = "UTF-8")
head(call171819raw)
tail(call171819raw)
```

```{r}
colnames(call171819raw) = c("date", "weekday", "time", "type", "sido","sigungu","dong","counts")
call171819 = call171819raw %>% mutate(date = ymd(date)) %>% select(date, sigungu, counts)
call171819
```


```{r}
options(dplyr.summarise.inform = FALSE)
Dates = unique(call171819$date)
call171819_gu = data.table()
for(i in 1:length(Dates)) {
  Date = Dates[i]
  if((i%%100)==1) cat(Date, "\t")
  datevalue = call171819 %>% filter(date == Date) %>% group_by(sigungu) %>% summarise(counts = sum(counts)) %>% spread(sigungu, counts)
  call171819_gu = bind_rows(call171819_gu, cbind(Date, datevalue))
}
call171819_gu = subset(call171819_gu, select= -c(광명시))
```
```{r}
head(call171819_gu)
write.table(call171819_gu, "data/call171819_gu.csv", sep=",", row.names = F, fileEncoding = "UTF-8")
```
```{r}
call171819_gu = fread("data/call171819_gu.csv", encoding = "UTF-8")
call171819_gu = call171819_gu %>% select(sort(tidyselect::peek_vars()))
call171819_gu
```


```{r}
Week = as.Date(cut(call171819_gu$Date, "week"))
call171819_gu_weekly = aggregate(.~ Week, call171819_gu[,-1], sum, na.action=NULL)
call171819_gu_weekly = call171819_gu_weekly[2:(nrow(call171819_gu_weekly)-1), ]
call171819_gu_weekly
```

```{r}
call171819_long_weekly = call171819_gu_weekly %>% gather("gu", "calls", -Week)

call171819_long_weekly %>% 
  filter(gu %in% sort(seoulCode$citySggName)[1:12]) %>% 
  ggplot(aes(x=ymd(Week), y= calls, color=gu))+
  geom_line()+  facet_wrap(~ gu, scales="free")+
  theme(legend.position="right")

call171819_long_weekly %>% 
  filter(gu %in% sort(seoulCode$citySggName)[13:24]) %>% 
  ggplot(aes(x=ymd(Week), y= calls, color=gu))+
  geom_line()+  facet_wrap(~ gu, scales="free")+
  theme(legend.position="right")
```


시....발거 이거 애새끼들이 통화를 안 하니까 통화량이 점점 줄어드네 시발겈ㅋㅋㅋㅋㅋㅋㅋㅋ 못쓴다곸ㅋㅋㅋㅋㅋ













